# Generated by Django 4.2.11 on 2024-04-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_categoria_libro_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='autor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='libro',
            name='precio',
            field=models.CharField(default='', max_length=300),
        ),
    ]
