# Generated by Django 4.2.11 on 2024-04-14 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_libro_autor_libros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Libros',
            new_name='Libroos',
        ),
    ]
