# Generated by Django 4.2.11 on 2024-04-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_descripcion_books_descripcionn_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autor',
            new_name='Autores',
        ),
        migrations.AlterField(
            model_name='books',
            name='imagenn',
            field=models.ImageField(blank=True, null=True, upload_to='libroos/'),
        ),
    ]
