# Generated by Django 4.2.11 on 2024-04-15 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='categoria_libro',
            name='imagen',
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_isbn', models.CharField(max_length=300)),
                ('precio', models.CharField(default='', max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='libros/')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autores', to='core.categoria_libro')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='core.categoria_libro')),
            ],
        ),
    ]
