# Generated by Django 4.2.11 on 2024-04-27 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='age',
        ),
    ]
