# Generated by Django 4.2.11 on 2024-04-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_userdata_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('run', models.IntegerField(primary_key=True, serialize=False, verbose_name='run')),
                ('username', models.CharField(max_length=10, verbose_name='username')),
                ('nombres', models.CharField(max_length=60, verbose_name='nombres')),
                ('apellidos', models.CharField(max_length=60, verbose_name='apellidos')),
                ('password', models.CharField(max_length=255, verbose_name='password')),
                ('perfil', models.IntegerField(blank=True, null=True, verbose_name='perfil')),
            ],
        ),
    ]
