# Generated by Django 4.2.11 on 2024-04-14 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_autor_remove_juego_categoria_juego_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=300)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.CharField(default='', max_length=300)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='libro/')),
                ('autor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='autores', to='core.autor')),
                ('categoriass_libros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libroo', to='core.categoria_libro')),
            ],
        ),
    ]
