# Generated by Django 4.2.11 on 2024-04-14 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_libroos_autor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Libroos',
            new_name='books',
        ),
    ]
