# Generated by Django 4.2.11 on 2024-04-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_libroos_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='descripcion',
            new_name='descripcionn',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='isbn',
            new_name='isbnn',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='nombre',
            new_name='nnombre',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='precio',
            new_name='precioo',
        ),
        migrations.RemoveField(
            model_name='books',
            name='imagen',
        ),
        migrations.AddField(
            model_name='books',
            name='imagenn',
            field=models.ImageField(blank=True, null=True, upload_to='libros/'),
        ),
    ]
