# Generated by Django 4.2.11 on 2024-04-15 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_categoria_libro_categoria_libro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='categoria_Libro',
            new_name='categoria_libro',
        ),
    ]
